/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_actor = 1,
  anon_sym_component = 2,
  anon_sym_store = 3,
  anon_sym_claim = 4,
  anon_sym_boundary = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_SEMI = 8,
  anon_sym_COLON = 9,
  anon_sym_DASH_GT = 10,
  anon_sym_LT_EQ_GT = 11,
  anon_sym_EQ_GT = 12,
  anon_sym_EQ_SLASH_EQ = 13,
  anon_sym_DOT_DOT_GT = 14,
  anon_sym_assert = 15,
  anon_sym_view = 16,
  anon_sym_state = 17,
  anon_sym_DASH_DASH_LBRACK = 18,
  anon_sym_RBRACK_DASH_DASH_GT = 19,
  anon_sym_not = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_and = 23,
  anon_sym_COMMA = 24,
  anon_sym_or = 25,
  anon_sym_implies = 26,
  anon_sym_knows = 27,
  anon_sym_believes = 28,
  anon_sym_world = 29,
  anon_sym_future_nec = 30,
  anon_sym_always = 31,
  anon_sym_common_knowledge = 32,
  sym_identifier = 33,
  sym_string = 34,
  anon_sym_LBRACK = 35,
  anon_sym_RBRACK = 36,
  sym_source_file = 37,
  sym__statement = 38,
  sym_entity_declaration = 39,
  sym_property = 40,
  sym_relation = 41,
  sym_assertion = 42,
  sym_view_projection = 43,
  sym_state_block = 44,
  sym_state_stmt = 45,
  sym_edge_decl = 46,
  sym_logic_expression = 47,
  sym_formula = 48,
  sym_array_literal = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_entity_declaration_repeat1 = 51,
  aux_sym_state_block_repeat1 = 52,
  aux_sym_array_literal_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_actor] = "actor",
  [anon_sym_component] = "component",
  [anon_sym_store] = "store",
  [anon_sym_claim] = "claim",
  [anon_sym_boundary] = "boundary",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_EQ_GT] = "<=>",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_EQ_SLASH_EQ] = "=/=",
  [anon_sym_DOT_DOT_GT] = "..>",
  [anon_sym_assert] = "assert",
  [anon_sym_view] = "view",
  [anon_sym_state] = "state",
  [anon_sym_DASH_DASH_LBRACK] = "--[",
  [anon_sym_RBRACK_DASH_DASH_GT] = "]-->",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_and] = "and",
  [anon_sym_COMMA] = ",",
  [anon_sym_or] = "or",
  [anon_sym_implies] = "implies",
  [anon_sym_knows] = "knows",
  [anon_sym_believes] = "believes",
  [anon_sym_world] = "world",
  [anon_sym_future_nec] = "future_nec",
  [anon_sym_always] = "always",
  [anon_sym_common_knowledge] = "common_knowledge",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_entity_declaration] = "entity_declaration",
  [sym_property] = "property",
  [sym_relation] = "relation",
  [sym_assertion] = "assertion",
  [sym_view_projection] = "view_projection",
  [sym_state_block] = "state_block",
  [sym_state_stmt] = "state_stmt",
  [sym_edge_decl] = "edge_decl",
  [sym_logic_expression] = "logic_expression",
  [sym_formula] = "formula",
  [sym_array_literal] = "array_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_entity_declaration_repeat1] = "entity_declaration_repeat1",
  [aux_sym_state_block_repeat1] = "state_block_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_actor] = anon_sym_actor,
  [anon_sym_component] = anon_sym_component,
  [anon_sym_store] = anon_sym_store,
  [anon_sym_claim] = anon_sym_claim,
  [anon_sym_boundary] = anon_sym_boundary,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_EQ_SLASH_EQ] = anon_sym_EQ_SLASH_EQ,
  [anon_sym_DOT_DOT_GT] = anon_sym_DOT_DOT_GT,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_view] = anon_sym_view,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_DASH_DASH_LBRACK] = anon_sym_DASH_DASH_LBRACK,
  [anon_sym_RBRACK_DASH_DASH_GT] = anon_sym_RBRACK_DASH_DASH_GT,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_implies] = anon_sym_implies,
  [anon_sym_knows] = anon_sym_knows,
  [anon_sym_believes] = anon_sym_believes,
  [anon_sym_world] = anon_sym_world,
  [anon_sym_future_nec] = anon_sym_future_nec,
  [anon_sym_always] = anon_sym_always,
  [anon_sym_common_knowledge] = anon_sym_common_knowledge,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_entity_declaration] = sym_entity_declaration,
  [sym_property] = sym_property,
  [sym_relation] = sym_relation,
  [sym_assertion] = sym_assertion,
  [sym_view_projection] = sym_view_projection,
  [sym_state_block] = sym_state_block,
  [sym_state_stmt] = sym_state_stmt,
  [sym_edge_decl] = sym_edge_decl,
  [sym_logic_expression] = sym_logic_expression,
  [sym_formula] = sym_formula,
  [sym_array_literal] = sym_array_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_entity_declaration_repeat1] = aux_sym_entity_declaration_repeat1,
  [aux_sym_state_block_repeat1] = aux_sym_state_block_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_actor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_component] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_store] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_claim] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boundary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_view] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_implies] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_knows] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_believes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_world] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_future_nec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_always] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_common_knowledge] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_entity_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_view_projection] = {
    .visible = true,
    .named = true,
  },
  [sym_state_block] = {
    .visible = true,
    .named = true,
  },
  [sym_state_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_logic_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_formula] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_state_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_expression = 1,
  field_from = 2,
  field_key = 3,
  field_kind = 4,
  field_label = 5,
  field_name = 6,
  field_operator = 7,
  field_relation = 8,
  field_to = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_expression] = "expression",
  [field_from] = "from",
  [field_key] = "key",
  [field_kind] = "kind",
  [field_label] = "label",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_relation] = "relation",
  [field_to] = "to",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 4},
  [6] = {.index = 11, .length = 3},
  [7] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_kind, 0},
    {field_name, 1},
  [3] =
    {field_expression, 1},
  [4] =
    {field_from, 0},
    {field_operator, 1},
    {field_to, 2},
  [7] =
    {field_from, 0},
    {field_label, 4},
    {field_operator, 1},
    {field_to, 2},
  [11] =
    {field_from, 0},
    {field_relation, 2},
    {field_to, 4},
  [14] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 2,
        '(', 37,
        ')', 38,
        ',', 40,
        '-', 3,
        '.', 6,
        ':', 25,
        ';', 24,
        '<', 9,
        '=', 7,
        '[', 145,
        ']', 147,
        'a', 56,
        'b', 62,
        'c', 83,
        'f', 134,
        'i', 89,
        'k', 98,
        'n', 110,
        'o', 114,
        's', 126,
        'v', 77,
        'w', 104,
        '{', 22,
        '}', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        ']', 4,
        'a', 82,
        'b', 63,
        'c', 107,
        'f', 134,
        'i', 89,
        'k', 98,
        'n', 110,
        'o', 114,
        'w', 104,
        '}', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(144);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '>') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == '[') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 2,
        ',', 40,
        ']', 146,
        'a', 57,
        'b', 103,
        'c', 84,
        's', 126,
        'v', 77,
        '{', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_actor);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_component);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_store);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_claim);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_boundary);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ_SLASH_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_assert);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_view);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_state);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK_DASH_DASH_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_implies);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_knows);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_believes);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_world);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_future_nec);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_always);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_common_knowledge);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(131);
      if (lookahead == 'o') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(132);
      if (lookahead == 'l') ADVANCE(139);
      if (lookahead == 'n') ADVANCE(58);
      if (lookahead == 's') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(132);
      if (lookahead == 's') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(87);
      if (lookahead == 'o') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(139);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(52);
      if (lookahead == 'o') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(52);
      if (lookahead == 'o') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(106);
      if (lookahead == 'p') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 15},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 14},
  [34] = {.lex_state = 14},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 14},
  [39] = {.lex_state = 15},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 14},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 14},
  [79] = {.lex_state = 14},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 14},
  [82] = {.lex_state = 14},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_actor] = ACTIONS(1),
    [anon_sym_component] = ACTIONS(1),
    [anon_sym_store] = ACTIONS(1),
    [anon_sym_claim] = ACTIONS(1),
    [anon_sym_boundary] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_EQ_SLASH_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT_GT] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_view] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_DASH_DASH_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_implies] = ACTIONS(1),
    [anon_sym_knows] = ACTIONS(1),
    [anon_sym_believes] = ACTIONS(1),
    [anon_sym_world] = ACTIONS(1),
    [anon_sym_future_nec] = ACTIONS(1),
    [anon_sym_always] = ACTIONS(1),
    [anon_sym_common_knowledge] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym__statement] = STATE(2),
    [sym_entity_declaration] = STATE(2),
    [sym_relation] = STATE(2),
    [sym_assertion] = STATE(2),
    [sym_view_projection] = STATE(2),
    [sym_state_block] = STATE(2),
    [sym_edge_decl] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_actor] = ACTIONS(5),
    [anon_sym_component] = ACTIONS(5),
    [anon_sym_store] = ACTIONS(5),
    [anon_sym_claim] = ACTIONS(5),
    [anon_sym_boundary] = ACTIONS(5),
    [anon_sym_assert] = ACTIONS(7),
    [anon_sym_view] = ACTIONS(9),
    [anon_sym_state] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_assert,
    ACTIONS(9), 1,
      anon_sym_view,
    ACTIONS(11), 1,
      anon_sym_state,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 5,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
    STATE(3), 8,
      sym__statement,
      sym_entity_declaration,
      sym_relation,
      sym_assertion,
      sym_view_projection,
      sym_state_block,
      sym_edge_decl,
      aux_sym_source_file_repeat1,
  [33] = 7,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(22), 1,
      anon_sym_assert,
    ACTIONS(25), 1,
      anon_sym_view,
    ACTIONS(28), 1,
      anon_sym_state,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(19), 5,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
    STATE(3), 8,
      sym__statement,
      sym_entity_declaration,
      sym_relation,
      sym_assertion,
      sym_view_projection,
      sym_state_block,
      sym_edge_decl,
      aux_sym_source_file_repeat1,
  [66] = 10,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    STATE(57), 1,
      sym_formula,
    STATE(75), 1,
      sym_logic_expression,
    STATE(8), 2,
      sym_state_stmt,
      aux_sym_state_block_repeat1,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [104] = 10,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_formula,
    STATE(75), 1,
      sym_logic_expression,
    STATE(8), 2,
      sym_state_stmt,
      aux_sym_state_block_repeat1,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [142] = 10,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_formula,
    STATE(75), 1,
      sym_logic_expression,
    STATE(4), 2,
      sym_state_stmt,
      aux_sym_state_block_repeat1,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [180] = 10,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    STATE(57), 1,
      sym_formula,
    STATE(75), 1,
      sym_logic_expression,
    STATE(5), 2,
      sym_state_stmt,
      aux_sym_state_block_repeat1,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [218] = 10,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      anon_sym_common_knowledge,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_string,
    STATE(57), 1,
      sym_formula,
    STATE(75), 1,
      sym_logic_expression,
    STATE(8), 2,
      sym_state_stmt,
      aux_sym_state_block_repeat1,
    ACTIONS(54), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(57), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(60), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [256] = 7,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    STATE(71), 1,
      sym_logic_expression,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [284] = 7,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    STATE(62), 1,
      sym_logic_expression,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [312] = 7,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    STATE(64), 1,
      sym_logic_expression,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [340] = 7,
    ACTIONS(42), 1,
      anon_sym_common_knowledge,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    STATE(73), 1,
      sym_logic_expression,
    ACTIONS(36), 3,
      anon_sym_not,
      anon_sym_future_nec,
      anon_sym_always,
    ACTIONS(38), 3,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
    ACTIONS(40), 3,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
  [368] = 2,
    ACTIONS(72), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(74), 11,
      anon_sym_not,
      anon_sym_and,
      anon_sym_or,
      anon_sym_implies,
      anon_sym_knows,
      anon_sym_believes,
      anon_sym_world,
      anon_sym_future_nec,
      anon_sym_always,
      anon_sym_common_knowledge,
      sym_identifier,
  [386] = 4,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      sym_string,
    ACTIONS(78), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [407] = 3,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(86), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [425] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [440] = 2,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [455] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [470] = 2,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [485] = 2,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [500] = 2,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [515] = 2,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [530] = 2,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [545] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [560] = 2,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [575] = 2,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [590] = 2,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [605] = 2,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [620] = 2,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [635] = 2,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 9,
      anon_sym_actor,
      anon_sym_component,
      anon_sym_store,
      anon_sym_claim,
      anon_sym_boundary,
      anon_sym_assert,
      anon_sym_view,
      anon_sym_state,
      sym_identifier,
  [650] = 2,
    ACTIONS(152), 1,
      anon_sym_DASH_DASH_LBRACK,
    ACTIONS(150), 5,
      anon_sym_DASH_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
      anon_sym_EQ_SLASH_EQ,
      anon_sym_DOT_DOT_GT,
  [661] = 3,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      sym_identifier,
    STATE(36), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [672] = 3,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [683] = 3,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(37), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [694] = 3,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(36), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [705] = 3,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 1,
      sym_identifier,
    STATE(36), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [716] = 3,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(36), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [727] = 3,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    STATE(35), 2,
      sym_property,
      aux_sym_entity_declaration_repeat1,
  [738] = 3,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      aux_sym_array_literal_repeat1,
  [748] = 3,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    ACTIONS(180), 1,
      sym_string,
  [758] = 1,
    ACTIONS(182), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [764] = 3,
    ACTIONS(184), 1,
      sym_string,
    ACTIONS(186), 1,
      anon_sym_LBRACK,
    STATE(70), 1,
      sym_array_literal,
  [774] = 1,
    ACTIONS(188), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [780] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      aux_sym_array_literal_repeat1,
  [790] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_array_literal_repeat1,
  [800] = 1,
    ACTIONS(196), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [806] = 1,
    ACTIONS(198), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [811] = 2,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
    ACTIONS(202), 1,
      anon_sym_SEMI,
  [818] = 2,
    ACTIONS(204), 1,
      sym_string,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
  [825] = 2,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(210), 1,
      anon_sym_SEMI,
  [832] = 1,
    ACTIONS(212), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [837] = 2,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      anon_sym_COLON,
  [844] = 1,
    ACTIONS(218), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [849] = 1,
    ACTIONS(174), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [854] = 1,
    ACTIONS(220), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [859] = 2,
    ACTIONS(186), 1,
      anon_sym_LBRACK,
    STATE(64), 1,
      sym_array_literal,
  [866] = 1,
    ACTIONS(222), 1,
      anon_sym_SEMI,
  [870] = 1,
    ACTIONS(224), 1,
      anon_sym_COLON,
  [874] = 1,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
  [878] = 1,
    ACTIONS(228), 1,
      anon_sym_LPAREN,
  [882] = 1,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
  [886] = 1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [890] = 1,
    ACTIONS(234), 1,
      anon_sym_SEMI,
  [894] = 1,
    ACTIONS(236), 1,
      anon_sym_COMMA,
  [898] = 1,
    ACTIONS(238), 1,
      sym_identifier,
  [902] = 1,
    ACTIONS(240), 1,
      anon_sym_SEMI,
  [906] = 1,
    ACTIONS(242), 1,
      sym_identifier,
  [910] = 1,
    ACTIONS(244), 1,
      anon_sym_SEMI,
  [914] = 1,
    ACTIONS(246), 1,
      anon_sym_SEMI,
  [918] = 1,
    ACTIONS(248), 1,
      anon_sym_SEMI,
  [922] = 1,
    ACTIONS(250), 1,
      anon_sym_SEMI,
  [926] = 1,
    ACTIONS(252), 1,
      anon_sym_SEMI,
  [930] = 1,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [934] = 1,
    ACTIONS(256), 1,
      sym_string,
  [938] = 1,
    ACTIONS(258), 1,
      anon_sym_SEMI,
  [942] = 1,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
  [946] = 1,
    ACTIONS(262), 1,
      sym_identifier,
  [950] = 1,
    ACTIONS(264), 1,
      sym_identifier,
  [954] = 1,
    ACTIONS(266), 1,
      sym_identifier,
  [958] = 1,
    ACTIONS(268), 1,
      sym_string,
  [962] = 1,
    ACTIONS(270), 1,
      sym_identifier,
  [966] = 1,
    ACTIONS(272), 1,
      sym_identifier,
  [970] = 1,
    ACTIONS(274), 1,
      anon_sym_LPAREN,
  [974] = 1,
    ACTIONS(276), 1,
      anon_sym_SEMI,
  [978] = 1,
    ACTIONS(278), 1,
      anon_sym_RBRACK_DASH_DASH_GT,
  [982] = 1,
    ACTIONS(280), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 218,
  [SMALL_STATE(9)] = 256,
  [SMALL_STATE(10)] = 284,
  [SMALL_STATE(11)] = 312,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 368,
  [SMALL_STATE(14)] = 386,
  [SMALL_STATE(15)] = 407,
  [SMALL_STATE(16)] = 425,
  [SMALL_STATE(17)] = 440,
  [SMALL_STATE(18)] = 455,
  [SMALL_STATE(19)] = 470,
  [SMALL_STATE(20)] = 485,
  [SMALL_STATE(21)] = 500,
  [SMALL_STATE(22)] = 515,
  [SMALL_STATE(23)] = 530,
  [SMALL_STATE(24)] = 545,
  [SMALL_STATE(25)] = 560,
  [SMALL_STATE(26)] = 575,
  [SMALL_STATE(27)] = 590,
  [SMALL_STATE(28)] = 605,
  [SMALL_STATE(29)] = 620,
  [SMALL_STATE(30)] = 635,
  [SMALL_STATE(31)] = 650,
  [SMALL_STATE(32)] = 661,
  [SMALL_STATE(33)] = 672,
  [SMALL_STATE(34)] = 683,
  [SMALL_STATE(35)] = 694,
  [SMALL_STATE(36)] = 705,
  [SMALL_STATE(37)] = 716,
  [SMALL_STATE(38)] = 727,
  [SMALL_STATE(39)] = 738,
  [SMALL_STATE(40)] = 748,
  [SMALL_STATE(41)] = 758,
  [SMALL_STATE(42)] = 764,
  [SMALL_STATE(43)] = 774,
  [SMALL_STATE(44)] = 780,
  [SMALL_STATE(45)] = 790,
  [SMALL_STATE(46)] = 800,
  [SMALL_STATE(47)] = 806,
  [SMALL_STATE(48)] = 811,
  [SMALL_STATE(49)] = 818,
  [SMALL_STATE(50)] = 825,
  [SMALL_STATE(51)] = 832,
  [SMALL_STATE(52)] = 837,
  [SMALL_STATE(53)] = 844,
  [SMALL_STATE(54)] = 849,
  [SMALL_STATE(55)] = 854,
  [SMALL_STATE(56)] = 859,
  [SMALL_STATE(57)] = 866,
  [SMALL_STATE(58)] = 870,
  [SMALL_STATE(59)] = 874,
  [SMALL_STATE(60)] = 878,
  [SMALL_STATE(61)] = 882,
  [SMALL_STATE(62)] = 886,
  [SMALL_STATE(63)] = 890,
  [SMALL_STATE(64)] = 894,
  [SMALL_STATE(65)] = 898,
  [SMALL_STATE(66)] = 902,
  [SMALL_STATE(67)] = 906,
  [SMALL_STATE(68)] = 910,
  [SMALL_STATE(69)] = 914,
  [SMALL_STATE(70)] = 918,
  [SMALL_STATE(71)] = 922,
  [SMALL_STATE(72)] = 926,
  [SMALL_STATE(73)] = 930,
  [SMALL_STATE(74)] = 934,
  [SMALL_STATE(75)] = 938,
  [SMALL_STATE(76)] = 942,
  [SMALL_STATE(77)] = 946,
  [SMALL_STATE(78)] = 950,
  [SMALL_STATE(79)] = 954,
  [SMALL_STATE(80)] = 958,
  [SMALL_STATE(81)] = 962,
  [SMALL_STATE(82)] = 966,
  [SMALL_STATE(83)] = 970,
  [SMALL_STATE(84)] = 974,
  [SMALL_STATE(85)] = 978,
  [SMALL_STATE(86)] = 982,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_stmt, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_stmt, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_block, 2, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_block, 2, 0, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_block, 3, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_block, 3, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation, 4, 0, 4),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relation, 4, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_block, 4, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_block, 4, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 5, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_declaration, 5, 0, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 4, 0, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_declaration, 4, 0, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_view_projection, 3, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_view_projection, 3, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_block, 6, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_block, 6, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_view_projection, 5, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_view_projection, 5, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion, 3, 0, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assertion, 3, 0, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_block, 5, 0, 1),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_block, 5, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation, 6, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relation, 6, 0, 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 3, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_declaration, 3, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 6, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_declaration, 6, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_decl, 6, 0, 6),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_edge_decl, 6, 0, 6),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_view_projection, 6, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_view_projection, 6, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 7, 0, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_declaration, 7, 0, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_declaration_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entity_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logic_expression, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logic_expression, 4, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logic_expression, 6, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 7),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formula, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_balloon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
