[package]
name = "tree-sitter-philo"
description = "Philo grammar for tree-sitter"
version = "0.0.1"
edition = "2021"
build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.26"
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.0"
